import {
  getShellReadyDelayMs,
  loadAgentDefaults,
  discoverAgentDefinitions,
  resolveAgentExtensions,
  buildAgentResourceArgs,
  formatElapsed,
} from "./agent.ts";
import {
  buildSubagentToolAllowlist,
  buildPiPromptArgs,
  resolveDenyTools,
  resolveLaunchBehavior,
  resolveEffectiveInteractive,
  resolveEffectiveSessionMode,
} from "./enforce.ts";
import { resolveResumeLaunchBehavior } from "./resume.ts";
import {
  runningSubagents,
  checkStatusThrottle,
  resetStatusCheckThrottle,
  getStatusThrottleRemainingMs,
  setStatusSnapshot,
  getStatusSnapshot,
  getStatusThrottleStrikes,
  getCoordDir,
  writeIncomingMessage,
  countPendingFiles,
  MAX_MESSAGE_CHARS,
  MAX_MESSAGES_PER_CALL,
  MAX_PENDING_FILES,
} from "./shared.ts";
import {
  borderLine,
  renderSubagentWidgetLines,
  resolveResultPresentation,
  updateWidget,
} from "./widget.ts";
import {
  handleSubagentInterrupt as rawInterrupt,
  resolveInterruptTarget as rawResolveTarget,
  requestSubagentInterrupt,
} from "./interrupt.ts";

export const __test__ = {
  borderLine,
  getShellReadyDelayMs,
  renderSubagentWidgetLines,
  loadAgentDefaults,
  discoverAgentDefinitions,
  resolveAgentExtensions,
  buildAgentResourceArgs,
  resolveEffectiveSessionMode,
  resolveLaunchBehavior,
  resolveEffectiveInteractive,
  buildSubagentToolAllowlist,
  buildPiPromptArgs,
  resolveDenyTools,
  resolveResumeLaunchBehavior,
  runningSubagents,
  formatElapsed,
  resolveResultPresentation,
  handleSubagentInterrupt: (
    params: { id?: string; name?: string },
    sendEscapeKey?: (surface: string) => void,
    closeSurfaceFn?: (surface: string) => void,
  ) => rawInterrupt(params, runningSubagents, () => updateWidget(null, runningSubagents, false), sendEscapeKey ?? (() => {}), closeSurfaceFn ?? (() => {})),
  resolveInterruptTarget: (params: { id?: string; name?: string }) => rawResolveTarget(params, runningSubagents),
  requestSubagentInterrupt,
  checkStatusThrottle,
  resetStatusCheckThrottle,
  getStatusThrottleRemainingMs,
  setStatusSnapshot,
  getStatusSnapshot,
  getStatusThrottleStrikes,
  getCoordDir,
  writeIncomingMessage,
  countPendingFiles,
  MAX_MESSAGE_CHARS,
  MAX_MESSAGES_PER_CALL,
  MAX_PENDING_FILES,
};
